-- Salin kode ini ke SQL Editor di Dashboard Supabase Anda
-- Ini akan membuat tabel yang dibutuhkan agar aplikasi berjalan

-- 1. Buat tabel produk
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price text not null,
  description text,
  seller text not null,
  image_url text
);

-- 2. Buat tabel pesan (chat)
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text text not null,
  sender text not null
);

-- 3. Aktifkan fitur keamanan (RLS)
alter table public.products enable row level security;
alter table public.messages enable row level security;

-- 4. Izinkan akses untuk semua orang (karena login pakai email sederhana)
create policy "Enable read access for all users" on public.products for select using (true);
create policy "Enable insert access for all users" on public.products for insert with check (true);

create policy "Enable read access for all users" on public.messages for select using (true);
create policy "Enable insert access for all users" on public.messages for insert with check (true);
